<?php

namespace Database\Seeders;

use App\Models\City;
use Illuminate\Database\Seeder;

class CitiesTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $ChileCities = [
            // Region 1: Tarapacá
            ['name' => 'Iquique', 'state_id' => 1],
            ['name' => 'Pozo Almonte', 'state_id' => 1],
            ['name' => 'Alto Hospicio', 'state_id' => 1],
            ['name' => 'Pica', 'state_id' => 1],
            ['name' => 'Huara', 'state_id' => 1],
            ['name' => 'Camiña', 'state_id' => 1],

            // Region 2: Antofagasta
            ['name' => 'Antofagasta', 'state_id' => 2],
            ['name' => 'Calama', 'state_id' => 2],
            ['name' => 'Tocopilla', 'state_id' => 2],
            ['name' => 'Mejillones', 'state_id' => 2],
            ['name' => 'María Elena', 'state_id' => 2],
            ['name' => 'San Pedro de Atacama', 'state_id' => 2],
            ['name' => 'Taltal', 'state_id' => 2],
            ['name' => 'Sierra Gorda', 'state_id' => 2],

            // Region 3: Atacama
            ['name' => 'Copiapó', 'state_id' => 3],
            ['name' => 'Vallenar', 'state_id' => 3],
            ['name' => 'Huasco', 'state_id' => 3],
            ['name' => 'Caldera', 'state_id' => 3],
            ['name' => 'Chañaral', 'state_id' => 3],
            ['name' => 'Diego de Almagro', 'state_id' => 3],
            ['name' => 'Freirina', 'state_id' => 3],
            ['name' => 'Tierra Amarilla', 'state_id' => 3],

            // Region 4: Coquimbo
            ['name' => 'La Serena', 'state_id' => 4],
            ['name' => 'Coquimbo', 'state_id' => 4],
            ['name' => 'Illapel', 'state_id' => 4],
            ['name' => 'Vicuña', 'state_id' => 4],
            ['name' => 'Salamanca', 'state_id' => 4],
            ['name' => 'Ovalle', 'state_id' => 4],
            ['name' => 'Monte Patria', 'state_id' => 4],
            ['name' => 'Punitaqui', 'state_id' => 4],
            ['name' => 'Combarbalá', 'state_id' => 4],

            // Region 5: Valparaíso
            ['name' => 'Valparaíso', 'state_id' => 5],
            ['name' => 'Viña del Mar', 'state_id' => 5],
            ['name' => 'Quilpué', 'state_id' => 5],
            ['name' => 'Villa Alemana', 'state_id' => 5],
            ['name' => 'Limache', 'state_id' => 5],
            ['name' => 'Los Andes', 'state_id' => 5],
            ['name' => 'San Felipe', 'state_id' => 5],
            ['name' => 'Quillota', 'state_id' => 5],
            ['name' => 'La Ligua', 'state_id' => 5],
            ['name' => 'La Calera', 'state_id' => 5],
            ['name' => 'Cabildo', 'state_id' => 5],
            ['name' => 'Quintero', 'state_id' => 5],
            ['name' => 'Puchuncaví', 'state_id' => 5],
            ['name' => 'Casablanca', 'state_id' => 5],
            ['name' => 'San Antonio', 'state_id' => 5],
            ['name' => 'Cartagena', 'state_id' => 5],
            ['name' => 'El Quisco', 'state_id' => 5],
            ['name' => 'Algarrobo', 'state_id' => 5],
            ['name' => 'El Tabo', 'state_id' => 5],
            ['name' => 'Llay Llay', 'state_id' => 5],
            ['name' => 'Nogales', 'state_id' => 5],

            // Region 6: Santiago Metropolitan
            ['name' => 'Santiago', 'state_id' => 6],
            ['name' => 'Puente Alto', 'state_id' => 6],
            ['name' => 'Maipú', 'state_id' => 6],
            ['name' => 'La Florida', 'state_id' => 6],
            ['name' => 'Las Condes', 'state_id' => 6],
            ['name' => 'Providencia', 'state_id' => 6],
            ['name' => 'La Pintana', 'state_id' => 6],
            ['name' => 'Peñalolén', 'state_id' => 6],
            ['name' => 'Quilicura', 'state_id' => 6],
            ['name' => 'Macul', 'state_id' => 6],
            ['name' => 'Ñuñoa', 'state_id' => 6],
            ['name' => 'Conchalí', 'state_id' => 6],
            ['name' => 'La Granja', 'state_id' => 6],
            ['name' => 'La Cisterna', 'state_id' => 6],
            ['name' => 'El Bosque', 'state_id' => 6],
            ['name' => 'San Bernardo', 'state_id' => 6],
            ['name' => 'Pudahuel', 'state_id' => 6],
            ['name' => 'Renca', 'state_id' => 6],
            ['name' => 'La Reina', 'state_id' => 6],
            ['name' => 'Independencia', 'state_id' => 6],
            ['name' => 'Quinta Normal', 'state_id' => 6],
            ['name' => 'Lo Espejo', 'state_id' => 6],
            ['name' => 'Pedro Aguirre Cerda', 'state_id' => 6],
            ['name' => 'Cerrillos', 'state_id' => 6],
            ['name' => 'Huechuraba', 'state_id' => 6],
            ['name' => 'Lo Prado', 'state_id' => 6],
            ['name' => 'Pudahuel', 'state_id' => 6],
            ['name' => 'Estación Central', 'state_id' => 6],
            ['name' => 'San Miguel', 'state_id' => 6],
            ['name' => 'Buin', 'state_id' => 6],

            // Region 7: Libertador General Bernardo O'Higgins
            ['name' => 'Rancagua', 'state_id' => 7],
            ['name' => 'Rengo', 'state_id' => 7],
            ['name' => 'San Fernando', 'state_id' => 7],
            ['name' => 'Machalí', 'state_id' => 7],
            ['name' => 'Graneros', 'state_id' => 7],
            ['name' => 'Santa Cruz', 'state_id' => 7],
            ['name' => 'Peumo', 'state_id' => 7],
            ['name' => 'San Vicente de Tagua Tagua', 'state_id' => 7],
            ['name' => 'Pichilemu', 'state_id' => 7],
            ['name' => 'Las Cabras', 'state_id' => 7],

            // Region 8: Maule
            ['name' => 'Talca', 'state_id' => 8],
            ['name' => 'Curicó', 'state_id' => 8],
            ['name' => 'Linares', 'state_id' => 8],
            ['name' => 'Molina', 'state_id' => 8],
            ['name' => 'Cauquenes', 'state_id' => 8],
            ['name' => 'Constitución', 'state_id' => 8],
            ['name' => 'Santa Cruz', 'state_id' => 8],
            ['name' => 'San Clemente', 'state_id' => 8],
            ['name' => 'San Javier', 'state_id' => 8],
            ['name' => 'Parral', 'state_id' => 8],

            // Region 9: Ñuble
            ['name' => 'Chillán', 'state_id' => 9],
            ['name' => 'Chillán Viejo', 'state_id' => 9],
            ['name' => 'Bulnes', 'state_id' => 9],
            ['name' => 'Cobquecura', 'state_id' => 9],
            ['name' => 'Coelemu', 'state_id' => 9],
            ['name' => 'Coihueco', 'state_id' => 9],
            ['name' => 'El Carmen', 'state_id' => 9],
            ['name' => 'Ninhue', 'state_id' => 9],
            ['name' => 'Ñiquén', 'state_id' => 9],
            ['name' => 'Pemuco', 'state_id' => 9],

            // Region 10: Biobío
            ['name' => 'Concepción', 'state_id' => 10],
            ['name' => 'Talcahuano', 'state_id' => 10],
            ['name' => 'Los Ángeles', 'state_id' => 10],
            ['name' => 'Chillán', 'state_id' => 10],
            ['name' => 'Coronel', 'state_id' => 10],
            ['name' => 'Curanilahue', 'state_id' => 10],
            ['name' => 'Lota', 'state_id' => 10],
            ['name' => 'Lebu', 'state_id' => 10],
            ['name' => 'Arauco', 'state_id' => 10],
            ['name' => 'Yumbel', 'state_id' => 10],
            ['name' => 'Hualpén', 'state_id' => 10],
            ['name' => 'San Pedro de la Paz', 'state_id' => 10],
            ['name' => 'Tome', 'state_id' => 10],
            ['name' => 'Santa Bárbara', 'state_id' => 10],
            ['name' => 'San Carlos', 'state_id' => 10],
            ['name' => 'Cabrero', 'state_id' => 10],
            ['name' => 'Laja', 'state_id' => 10],
            ['name' => 'Mulchén', 'state_id' => 10],
            ['name' => 'Nacimiento', 'state_id' => 10],
            ['name' => 'Los Álamos', 'state_id' => 10],
            ['name' => 'Antuco', 'state_id' => 10],
            ['name' => 'Cabrero', 'state_id' => 10],
            ['name' => 'Cañete', 'state_id' => 10],
            ['name' => 'Chiguayante', 'state_id' => 10],
            ['name' => 'Contulmo', 'state_id' => 10],
            ['name' => 'Curanilahue', 'state_id' => 10],
            ['name' => 'Florida', 'state_id' => 10],
            ['name' => 'Hualqui', 'state_id' => 10],
            ['name' => 'Laja', 'state_id' => 10],
            ['name' => 'Lebu', 'state_id' => 10],
            ['name' => 'Los Álamos', 'state_id' => 10],
            ['name' => 'Los Ángeles', 'state_id' => 10],
            ['name' => 'Lota', 'state_id' => 10],
            ['name' => 'Mulchén', 'state_id' => 10],
            ['name' => 'Negrete', 'state_id' => 10],
            ['name' => 'Penco', 'state_id' => 10],
            ['name' => 'Quilaco', 'state_id' => 10],
            ['name' => 'Quilleco', 'state_id' => 10],
            ['name' => 'San Pedro de la Paz', 'state_id' => 10],
            ['name' => 'San Rosendo', 'state_id' => 10],

            // Region 11: Araucanía
            ['name' => 'Temuco', 'state_id' => 11],
            ['name' => 'Padre Las Casas', 'state_id' => 11],
            ['name' => 'Angol', 'state_id' => 11],
            ['name' => 'Villarrica', 'state_id' => 11],
            ['name' => 'Pucón', 'state_id' => 11],
            ['name' => 'Collipulli', 'state_id' => 11],
            ['name' => 'Lautaro', 'state_id' => 11],
            ['name' => 'Victoria', 'state_id' => 11],
            ['name' => 'Curacautín', 'state_id' => 11],
            ['name' => 'Loncoche', 'state_id' => 11],
            ['name' => 'Cunco', 'state_id' => 11],
            ['name' => 'Traiguén', 'state_id' => 11],
            ['name' => 'Carahue', 'state_id' => 11],
            ['name' => 'Nueva Imperial', 'state_id' => 11],
            ['name' => 'Pitrufquén', 'state_id' => 11],
            ['name' => 'Gorbea', 'state_id' => 11],
            ['name' => 'Perquenco', 'state_id' => 11],
            ['name' => 'Vilcún', 'state_id' => 11],
            ['name' => 'Melipeuco', 'state_id' => 11],
            ['name' => 'Lonquimay', 'state_id' => 11],
            ['name' => 'Purén', 'state_id' => 11],
            ['name' => 'Renaico', 'state_id' => 11],
            ['name' => 'Saavedra', 'state_id' => 11],
            ['name' => 'Teodoro Schmidt', 'state_id' => 11],
            ['name' => 'Cholchol', 'state_id' => 11],
            ['name' => 'Freire', 'state_id' => 11],
            ['name' => 'Galvarino', 'state_id' => 11],
            ['name' => 'Lumaco', 'state_id' => 11],
            ['name' => 'Toltén', 'state_id' => 11],

            // Region 12: Los Ríos
            ['name' => 'Valdivia', 'state_id' => 12],
            ['name' => 'La Unión', 'state_id' => 12],
            ['name' => 'Río Bueno', 'state_id' => 12],
            ['name' => 'Lanco', 'state_id' => 12],
            ['name' => 'Panguipulli', 'state_id' => 12],
            ['name' => 'Los Lagos', 'state_id' => 12],
            ['name' => 'Corral', 'state_id' => 12],
            ['name' => 'Mariquina', 'state_id' => 12],
            ['name' => 'Máfil', 'state_id' => 12],
            ['name' => 'Paillaco', 'state_id' => 12],
            ['name' => 'Futrono', 'state_id' => 12],
            ['name' => 'Lago Ranco', 'state_id' => 12],

            // Region 13: Los Lagos
            ['name' => 'Puerto Montt', 'state_id' => 13],
            ['name' => 'Osorno', 'state_id' => 13],
            ['name' => 'Puerto Varas', 'state_id' => 13],
            ['name' => 'Castro', 'state_id' => 13],
            ['name' => 'Ancud', 'state_id' => 13],
            ['name' => 'Quellón', 'state_id' => 13],
            ['name' => 'Calbuco', 'state_id' => 13],
            ['name' => 'Frutillar', 'state_id' => 13],
            ['name' => 'Llanquihue', 'state_id' => 13],
            ['name' => 'Purranque', 'state_id' => 13],

            // Region 14: Aysén del General Carlos Ibáñez del Campo
            ['name' => 'Coyhaique', 'state_id' => 14],
            ['name' => 'Puerto Aysén', 'state_id' => 14],
            ['name' => 'Chile Chico', 'state_id' => 14],
            ['name' => 'Cochrane', 'state_id' => 14],
            ['name' => 'Puerto Cisnes', 'state_id' => 14],
            ['name' => 'Puerto Ibáñez', 'state_id' => 14],
            ['name' => 'Villa O\'Higgins', 'state_id' => 14],

            // Region 15: Magallanes y de la Antártica Chilena
            ['name' => 'Punta Arenas', 'state_id' => 15],
            ['name' => 'Puerto Natales', 'state_id' => 15],
            ['name' => 'Porvenir', 'state_id' => 15],
            ['name' => 'Puerto Williams', 'state_id' => 15],
            ['name' => 'Cabo de Hornos', 'state_id' => 15],
            ['name' => 'Río Verde', 'state_id' => 15],
            ['name' => 'San Gregorio', 'state_id' => 15],

            // Region 16: Arica y Parinacota
            ['name' => 'Arica', 'state_id' => 16],
            ['name' => 'Putre', 'state_id' => 16],
            ['name' => 'Camarones', 'state_id' => 16],
            ['name' => 'General Lagos', 'state_id' => 16],
            ['name' => 'Codpa', 'state_id' => 16],
        ];

        City::insert($ChileCities);
    }
}
